on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ror es
        uses: actions/checkout@v2
        with:
          path: main
          
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          path: docs 
          repository: beshu-tech/readonlyrest-docs
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          
          
      - run: |
          echo "$PWD ls..."
          ls
          echo "\n---------------"
          echo "ls -a docs.." && ls -a docs && echo "\n---------------"
          echo "ls -a main..." && ls -a main && echo "\n---------------"
          mv docs main/readonlyrest-docs
          cd main && echo "in main now" && ls
          git config --global advice.detachedHead false
          bash -x ci/actionstrings/run.sh
          rm -rf .git || true # so git wont think it's a submodule
          ls -a
          cd readonlyrest-docs
          ls -a
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "changing anoher repo" || true
          git push || true
